### ISSUE TITLE
RequestError: connect ECONNREFUSED 127.0.0.1:443

### ISSUE THREAD

**Issue by rpadovani** [tauri-apps/vue-cli-plugin-tauri#41]
**Describe the bug**
I try to use `yarn tauri:serve` command, but it fails. Using `tauri dev` + `vue-cli-service serve`, everything works fine. I've tried with NPM as well. The error is:

```
Downloading Rust CLI...
 ERROR  RequestError: connect ECONNREFUSED 127.0.0.1:443
RequestError: connect ECONNREFUSED 127.0.0.1:443
    at ClientRequest.<anonymous> (/home/rpadovani/Documents/daintree/node_modules/got/dist/source/core/index.js:956:111)
    at Object.onceWrapper (node:events:514:26)
    at ClientRequest.emit (node:events:406:35)
    at ClientRequest.origin.emit (/home/rpadovani/Documents/daintree/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1142:16)
```

**To Reproduce**

- Run `yarn tauri:serve`

**Environment (please complete the following information):**
 - vue-cli-plugin-tauri version : `1.0.0-beta.6`
 - other vue plugins used: 
 - (if possible) link to your repo: https://gitlab.com/rpadovani/daintree/ - branch `feature/tauri`
 - output from `npx tauri info`/`yarn tauri info`:

```
➜ yarn tauri info
yarn run v1.22.5
$ /home/rpadovani/Documents/daintree/node_modules/.bin/tauri info
Downloading Rust CLI...
Download Complete
 app:spawn Running "/home/rpadovani/Documents/daintree/node_modules/@tauri-apps/cli/bin/tauri-cli tauri info" +0ms


Operating System - Ubuntu, version 20.04 X64

Node.js environment
  Node.js - 16.6.1
  @tauri-apps/cli - 1.0.0-beta.7
  @tauri-apps/api - 1.0.0-beta.6

Global packages
  npm - 7.20.3
  yarn - 1.22.5

Rust environment
  rustc - 1.54.0
  cargo - 1.54.0

App directory structure
/src
/src-tauri
/.gitlab
/dist
/.git
/.idea
/node_modules
/public

App
  tauri.rs - 1.0.0-beta.7
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - Set automatically by Vue CLI plugin
  devPath - http://localhost:8080
  framework - Vue.js (Vue CLI)
  bundler - Webpack

Done in 6.89s.

```

**Comment by nothingismagick** [comment]
`yarn tauri:serve` is a reference to a command in your `package.json`. What are the contents of the value under that key in the `scripts` section?

**Comment by nothingismagick** [comment]
Is it the stock script, or have you modified it?

**Comment by rpadovani** [comment]
Thanks for the fast answer! It is the stock script: `vue-cli-service tauri:serve`

**Comment by nothingismagick** [comment]
ok, let's wait for @nklayman to respond then.

**Comment by nklayman** [comment]
I took a look at this a little while ago and couldn't figure out what was wrong. I think updating the tauri.js cli version in the plugin will fix it, but we have to wait for #44, which can't be merged till we publish a new version of tauri.js, which is blocked by the security audit.
